### ISSUE TITLE
Please add a Sample test app

### ISSUE THREAD

**Issue by simonbuehler** [agrath/Sniper.Lighting.Dmx#2]
hi,

browsed through the code and it seems to be really helpfull, it would be great though if there were some docs or a simple Test App on how to actually use the library.

Could you commit a sample app?

**Comment by agrath** [comment]
Good idea! I've used it in a bigger project but I can seperate out a simple test case. What sort of things would you like to see?

**Comment by simonbuehler** [comment]
just a basic sample with some comments that allows to run effects (pulsing a channel, fading in and out ), chaining(?) effects and generally helps as a explanation of how this is meant to be used ( whats better - static or instantiated style, how and whatfor the GUIDs are used, etc)

**Comment by simonbuehler** [comment]
do you think you could just provide me with some basic lines, doesn't have to by anything fancy ?

**Comment by agrath** [comment]
Sorry, really busy doing an on-site contract role and no time in the evenings! Try this, i've just thrown it together really quick and haven't tested as I don't have a device here, but it should be enough to get you started

[Sniper.Lighting.Dmx.Demo.zip](https://github.com/agrath/Sniper.Lighting.Dmx/files/143419/Sniper.Lighting.Dmx.Demo.zip)

**Comment by simonbuehler** [comment]
:+1: 
thats a great starting point to work from , thanks!

**Comment by simonbuehler** [comment]
i'd need a hint how to plug the ``LightOperation[] demos `` into the 
```
if (connected)
                {
                   //use demos here ..somehow
                }
```
part?

i tried 
```
if (connected)
                {
                    foreach (var lightOperation in demos)
                    {
                        lightOperation.Run(Guid.NewGuid(), 1);
                    }
                }
```

but that does nothing, should that work this way?

**Comment by agrath** [comment]
Hi @simonbuehler I see a comment in the history but not on this page, did you amend it?

**Comment by simonbuehler** [comment]
yes it all worked out fine so far

**Comment by agrath** [comment]
https://github.com/agrath/Sniper.Lighting.Dmx/wiki/Sample-c%23-usage
