### ISSUE TITLE
Program example

### ISSUE THREAD

**Issue by RanABI** [agrath/Sniper.Lighting.Dmx#3]
Hi,
I am trying to control DMX-512 components via USB port for the first time, It would be nice if you could add a running example to how to use this library. Thanks alot.

**Comment by agrath** [comment]
Hi @RanABI 

You can see a previous (closed) issue raised for the same here: https://github.com/agrath/Sniper.Lighting.Dmx/issues/2
On this issue you will find a link to a demo application (with source) that should still work.
https://github.com/agrath/Sniper.Lighting.Dmx/issues/2#issuecomment-187906320
There is also a short wiki article with the bare minimum code required to get started here (also linked from the previous issue)
https://github.com/agrath/Sniper.Lighting.Dmx/wiki/Sample-c%23-usage

I don't really maintain this project or source, it is part of an internal solution for a client which I decided to open source but it is not set up as a proper library with nuget, readme etc.
